server:
  port: 8888
  servlet:
    context-path: /api


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      url: "jdbc:mysql://121.196.109.61:3306/boot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false"
      max-active: 10
      filters: wall,stat,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        session-stat-max-count: 100
        exclusions: "*.js"
        session-stat-enable:
      stat-view-servlet:
        url-pattern: /druid/*
        enabled: true
        reset-enable: false
        login-username: admin
        login-password: admin



mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
